### PR TITLE
Modifying hover background color

### PR DESCRIPTION
**Pull request by AnilSonix**
Modifying
editor.hoverHighlightBackground"

Fix for
https://github.com/dracula/visual-studio-code/issues/152

https://github.com/dracula/visual-studio-code/issues/154

### CODE REVIEW

**Comment by dsifford** [comment]
2 things:

1. I'd like to at least be able to reproduce this problem myself before merging this PR.
2. Please upload a screenshot of the changes.

**Comment by AnilSonix** [comment]
@dsifford 
I'm having this bug in both Ubuntu and Windows machine.
With extensions disabled, it doesn't happen.
Screenshot from 2020-05-23 09-05-10
Screenshot from 2020-05-23 09-05-31

Is there way to know which extension might be responsible?

**Comment by dsifford** [comment]
@AnilSonix So just to be clear, with all extensions disabled, but with dracula enabled, it doesn't happen?

**Comment by AnilSonix** [comment]
@dsifford Yes , all disabled except Dracula theme
Screenshot from 2020-05-23 22-18-30

**Comment by dsifford** [comment]
Aha, I finally was able to repro this.

This looks fine to me. I'll release an update shortly. Thanks!

**Pull request merged**
