### PR TITLE
Add debugging profile for development

### PR DESCRIPTION
**Pull request by DanielRamosAcosta**
The debugging profile replaces the old bootstrap script (that no longer works).

The new workflow is:

1. Run `npm run dev`
2. Press F5 while the project is open

A new instance of VSCode is opened with hot-reloading capabilities over the theme. Changes on `dracula.yml` will be reflected almost instantaneously in the debugging instance.

Small demo: https://i.imgur.com/K8r5EGY.gifv

### CODE REVIEW

**Comment by dsifford** [comment]
Sweet. LGTM!

**Comment by dsifford** [comment]
Just tested this and it doesn't work for me :cry:

**Comment by DanielRamosAcosta** [comment]
But what does not work? The watch script `npm run dev` or the VS Code debugging profile?

**Comment by dsifford** [comment]
debugging profile. It opens an electron instance and does nothing for a while and then errors out.

**Pull request merged**
