### PR TITLE
Add support for statusBarItem.remoteBackground

### LINKED ISSUE #104: Add support for statusBarItem.remoteBackground
With the recent support for [VS Code Remote Development](https://code.visualstudio.com/blogs/2019/05/02/remote-development), there's a new color token for remote indicators. You can now set the foreground & background color for a remote indicator via `statusBarItem.remoteForeground`, `statusBarItem.remoteBackground`:

image

I'll submit a PR with some suggested colors (based on the activity bar badge colors), let me know if you've got any questions or concerns.

### PR DESCRIPTION
**Pull request by misolori**
Fixes #104 

image

image

### CODE REVIEW

**Comment by dsifford** [comment]
Thanks @misolori!

What about trying the purple or cyan color? That way it's still noticeable enough to tell that you're operating remotely, but not so jarring that it becomes distracting.

Your call. Just my 2 cents.

**Comment by misolori** [comment]
@dsifford yea, any of those colors will have low contrast (I was trying to borrow the colors from the activity bar badge). Here's a few other options, let me know what you prefer:

## Red
image

## Purple
image

## Purple text
image

## Pink text
image

**Comment by dsifford** [comment]
I'll let you make the call and if people come with pitchforks, we can just adjust :blush: 

Let me know when we're good to go and I'll merge :+1:

**Comment by misolori** [comment]
😀 

Let's go with purple since pink is already used more:

image

**Comment by dsifford** [comment]
Sweet! Thanks.. I'll get this merged and published in a bit. (keeping it unmerged so I don't forget)

**Comment by betancour** [comment]
I'll be waiting for the choice of a good color, the actual pink is horrible.... 

meanwhile I'll use the backgournd color... 

Ty all for regarding special to @dsifford

**Comment by betancour** [comment]
I did't like it that purple color so I put the pink as text color ... 

image

**Comment by rediffusion** [comment]
@misolori 

I like red thanks:

`#FF5554`

**Pull request merged**
