### PR TITLE
add editorActiveLineNumber.foreground

### PR DESCRIPTION
**Pull request by klebercode**

### CODE REVIEW

**Comment by dsifford** [comment]
Thanks for the contribution!

I'm inclined to say we should keep as-is since the yellow could be jarring to some users who have gotten used to the theme in its current form.

I'll keep this open for now to see if it draws any further feedback.

A solution for you in the interim is just to add an override for this to your user settings.

**Comment by klebercode** [comment]
Okay guy.

Thanks for the feedback.

**Comment by ajitid** [comment]
How about `#95aeff`?

screenshot from 2018-04-22 05-56-36

**Comment by klebercode** [comment]
I like this!

**Comment by dsifford** [comment]
I'd prefer to not add a non-spec color if we chose to try this. 

The yellow is a fine idea, but let's wait until the PR has a few more :+1: before giving it a try. Want to make sure this is something everybody would want, rather than just a few people.

**Comment by seiks** [comment]
On-spec colors comparison below.

Näyttökuva 2019-04-12 kello 21 19 34
Näyttökuva 2019-04-12 kello 21 20 01
Näyttökuva 2019-04-12 kello 21 20 11
Näyttökuva 2019-04-12 kello 21 20 19
Näyttökuva 2019-04-12 kello 21 20 29
Näyttökuva 2019-04-12 kello 21 20 41
Näyttökuva 2019-04-12 kello 21 20 51
Näyttökuva 2019-04-12 kello 21 21 00

**Comment by seiks** [comment]
Personally I would go with simple white (foreground color). Regardless of what color, I do think that this is an useful addition as it helps you gauge which line you're on even better. Reason my line highlight is so dark is because I had real trouble seeing the active line with vanilla Dracula. Having a highlight in the margin makes sense.

**Comment by seiks** [comment]
Another comparison, with vanilla theme (no custom modifications, no line highlight):

Näyttökuva 2019-04-12 kello 21 28 36
Näyttökuva 2019-04-12 kello 21 28 46
Näyttökuva 2019-04-12 kello 21 28 54
Näyttökuva 2019-04-12 kello 21 29 03
Näyttökuva 2019-04-12 kello 21 29 10
Näyttökuva 2019-04-12 kello 21 29 17
Näyttökuva 2019-04-12 kello 21 29 29
Näyttökuva 2019-04-12 kello 21 29 36

**Comment by leandrocunha** [comment]
I liked of purple version to keep the UI consistency

Purple Version

**Comment by JimmyMultani** [comment]
I vote for either Cyan or Purple.

**Comment by dsifford** [comment]
This is picking up a bit of traction. Thoughts @zenorocha?

**Comment by bdielman** [comment]
@dsifford - Adding a comment here to keep this thread active. I'm currently working on the Dracula theme for Nova and am struggling to pick a color for the active line number. When I took over it was a non-spec color so to have an 'official' color would take the guess work out of it.

FWIW - Vim uses yellow for the active line number though that seems to be determined by the editor itself rather than the maintainers.

**Comment by dsifford** [comment]
@bdielman Thanks! Ya we should prob make a decision here. I use vim as my daily driver and I've grown accustomed to yellow, but not opposed to go with majority rule here.

**Comment by luxonauta** [comment]
> @bdielman Thanks! Ya we should prob make a decision here. I use vim as my daily driver and I've grown accustomed to yellow, but not opposed to go with majority rule here.

I like the idea of being multicoloured 😅, but yellow is right. So we can move forward with this PR; later, I will discuss adding this to Dracula's Spec with Zeno.

**Comment by luxonauta** [comment]
Closing in favor of (#253)

**Pull request closed without merging**
