### PR TITLE
modified:function color to solve the problem that in the Variables module ,the function color isn't show 

### PR DESCRIPTION
**Pull request by dongqizhen**

### CODE REVIEW

**Comment by dsifford** [comment]
Thanks for the contribution @dongqizhen 

I'm not familiar with that module. Can you provide a quick before and after? 

Thanks in advance!

**Comment by dsifford** [comment]
@dongqizhen Thanks for the images. 

(the following comments are under the assumption that the images you pasted above are of javascript)

So, there's a couple things wrong here I think.

First, and most importantly: I believe your syntax highlight issues are stemming from another extension that you're using that thrashes the scopes of the builtin javascript syntax. The reason I think this is because the syntax highlighting is correct as-is on my end:

image

The most likely culprit is the extension you're using to colorize matching parens. Can you disable that extension and see if that solves the issue?

Second: The `FastClick` group should receive class syntax (blue italic, as you can see in my image above).

If you're using some javascript-like language that isn't actually JavaScript, then I think this could be mergable if you just go in and fix the syntax color (blue italic). If, on the other hand, it _is_ the paren colorizor extension that's causing this, I think the fix should happen on their end, rather than adding adjusting for a broken syntax on this end.

Let me know.

Thanks

**Comment by dongqizhen** [comment]
I don't know  why that is ，Maybe as you said ,that is Others extension cause the problem,thank you very much

**Comment by dongqizhen** [comment]
abierbaum.vscode-file-peek@1.0.1
abusaidm.html-snippets@0.2.1
aeschli.vscode-css-formatter@1.0.1
AESSoft.aessoft-class-autocomplete@0.1.0
airship.airship-react-snippets@0.0.8
akamud.vscode-caniuse@0.5.3
alefragnani.project-manager@0.25.2
amandeepmittal.console-snippets@1.3.0
ashhitch.vs-code-css-comments@1.0.3
bajdzis.vscode-refresh-html@0.0.2
bierner.color-info@0.5.0
blanu.vscode-styled-jsx@0.2.2
ChakrounAnas.turbo-console-log@1.2.5
chenxsan.vscode-standardjs@1.2.1
christian-kohler.npm-intellisense@1.3.0
christian-kohler.path-intellisense@1.4.2
coderfee.open-html-in-browser@0.1.21
CoenraadS.bracket-pair-colorizer@1.0.37
DaGhostman.vs-treeview@2.3.0
dariofuzinato.vue-peek@1.0.2
dbaeumer.jshint@0.10.18
dbaeumer.vscode-eslint@1.4.8
discountry.react-redux-react-router-snippets@0.4.29
dkundel.vscode-npm-source@1.0.0
donjayamanne.githistory@0.4.0
donjayamanne.jquerysnippets@0.0.1
dracula-theme.theme-dracula@2.9.0
dsznajder.es7-react-js-snippets@1.5.1
eamodio.gitlens@8.2.4
ecmel.vscode-html-css@0.2.0
eg2.tslint@1.0.28
eg2.vscode-npm-script@0.3.3
eheitherd.vscode-livescript-preview@1.0.2
emmanuelbeziat.vscode-great-icons@2.1.31
enochc.copy-relative-path@0.1.1
EQuimper.react-native-react-redux@1.8.0
EQuimper.react-native-react-redux-snippets-for-es6-es7-version-standard@1.0.3
esbenp.prettier-vscode@1.3.1
fab1o.dark-plus-with-italics@2.0.3
fantasytyx.tortoise-svn@0.1.1
felipecaputo.git-project-manager@1.5.1
file-icons.file-icons@1.0.12
fknop.vscode-npm@3.3.0
formulahendry.auto-close-tag@0.5.6
formulahendry.auto-complete-tag@0.0.2
formulahendry.auto-rename-tag@0.0.15
formulahendry.code-runner@0.9.3
ginfuru.ginfuru-onedark-raincoat-theme@0.2.36
glen-84.sass-lint@1.0.1
gluons.vscode-atom-javascript-snippet@0.2.1
gluons.vscode-atom-sass-snippet@0.0.3
hdg.live-html-previewer@0.3.0
heberalmeida.vue-snippets-js-html-pug-razor@0.0.3
hollowtree.vue-snippets@0.1.5
HookyQR.beautify@1.3.0
HookyQR.minify@0.3.0
Hridoy.animate-css@1.0.0
huren.youdao-translator@0.11.1
IBM.output-colorizer@0.1.2
ionutvmi.path-autocomplete@1.9.0
jack89ita.open-file-from-path@1.1.0
jasonnutter.search-node-modules@1.3.0
jeremyrajan.react-component@1.0.1
joelday.docthis@0.6.0
joshpeng.sublime-babel-vscode@0.2.9
jpoissonnier.vscode-styled-components@0.0.17
jundat95.react-native-snippet@0.4.2
lablup.live-code-runner@4.3.1
leizongmin.node-module-intellisense@1.5.0
liuji-jim.vue@0.1.5
lonefy.vscode-JS-CSS-HTML-formatter@0.2.3
lXSPandora.vscode-styled-components-snippets@1.0.2
marclipovsky.string-manipulation@0.2.0
michelemelluso.code-beautifier@2.0.3
mikey.vscode-fileheader@0.0.2
milobo.react-native-styled-component-snippets@1.0.1
mohsen1.prettify-json@0.0.3
mrmlnc.vscode-scss@0.6.2
ms-vscode.node-debug2@1.20.0
msjsdiag.debugger-for-chrome@4.3.0
naumovs.node-modules-resolve@1.0.2
negokaz.live-server-preview@0.1.2
NuclleaR.vscode-extension-auto-import@1.4.1
oysun.vuehelper@0.1.0
P-de-Jong.vscode-html-scss@0.0.42
PKief.material-icon-theme@3.3.0
pranaygp.vscode-css-peek@2.1.0
profimedica.live-preview@0.0.3
pselibas.livescript@0.1.1
qinjia.view-in-browser@0.0.5
ramyaraoa.sass-helper@0.0.2
ritwickdey.live-sass@1.3.0
ritwickdey.LiveServer@3.2.1
robertohuertasm.vscode-icons@7.22.0
saikou9901.evilinspector@1.0.4
santosh.react-native-snippet@0.6.0
sasa.vscode-sass-format@1.1.4
sdras.vue-vscode-snippets@1.3.0
shalldie.background@1.1.17
Shan.code-settings-sync@2.9.0
sidthesloth.html5-boilerplate@1.0.1
SirTori.indenticator@0.5.1
skyran.js-jsx-snippets@0.0.9
sporiley.css-auto-prefix@0.1.4
spywhere.guides@0.9.1
staychan.vue-color@0.0.3
steoates.autoimport@1.5.3
taichi.react-beautify@0.3.0
techer.open-in-browser@1.1.0
tht13.python@0.2.3
TimonVS.ReactSnippetsStandard@1.1.0
timothymclane.react-redux-es6-snippets@2.1.0
tomma5o.sassyah@0.0.3
vaniship.vue-ls@0.1.4
vsmobile.vscode-react-native@0.6.9
waderyan.gitblame@2.4.2
waderyan.nodejs-extension-pack@0.1.9
WallabyJs.quokka-vscode@1.0.121
wangkechun.html-less-class-completion@0.0.6
wangtao0101.vscode-js-import@0.15.1
xabikos.JavaScriptSnippets@1.6.0
xabikos.ReactSnippets@2.1.0
Youssef.viow@0.1.4

**Comment by dsifford** [comment]
Holy smokes! That's a lot of extensions!

I'll look into this more later this week when I get some extra time. Thanks for your patience.

**Comment by dongqizhen** [comment]
aha !!!!!!!!!!!!!!!! it's so useful to me

**Comment by dongqizhen** [comment]
thank you , My English is very poor, maybe the expression is not clear, Hope you bear with me

**Pull request closed without merging**
